export const revenueInputField = [
  "r1_title",
  "r1_value",
  "r2_title",
  "r2_value",
  "r3_title",
  "r3_value",
  "r4_title",
  "r4_value",
  "r5_title",
  "r5_value",
  "r6_title",
  "r6_value",
  "r7_title",
  "r7_value",
  "r8_title",
  "r8_value",
  "r9_title",
  "r9_value",
  "r10_title",
  "r10_value",
];
export const expenditureInputField = [
  "e1_title",
  "e1_value",
  "e2_title",
  "e2_value",
  "e3_title",
  "e3_value",
  "e4_title",
  "e4_value",
  "e5_title",
  "e5_value",
  "e6_title",
  "e6_value",
  "e7_title",
  "e7_value",
  "e8_title",
  "e8_value",
  "e9_title",
  "e9_value",
  "e10_title",
  "e10_value",
  "e11_title",
  "e11_value",
  "e12_title",
  "e12_value",
  "e13_title",
  "e13_value",
  "e14_title",
  "e14_value",
  "e15_title",
  "e15_value",
  "e16_title",
  "e16_value",
  "e17_title",
  "e17_value",
  "e18_title",
  "e18_value",
  "e19_title",
  "e19_value",
  "e20_title",
  "e20_value",
];
export const updateRevenueExpenditureForm = [
  { type: "date", value: "date" },
  { type: "text", value: "title" },
  { type: "text", value: "value" },
];

export const carInfoInputFieldCol1 = [
  { type: "text", label: "Veichle Name", value: "veichle_name" },
  { type: "text", label: "Chassis No", value: "chasis_no" },
  { type: "text", label: "Engine No", value: "engine_no" },
  { type: "text", label: "Model Year", value: "model_year" },
  { type: "text", label: "Registration No", value: "reg_no" },
  { type: "text", label: "Importer Name", value: "importer_name" },
  { type: "textarea", label: "Importer Address", value: "importer_address" },
  { type: "text", label: "Exporter Name", value: "exporter_name" },
  { type: "date", label: "From", value: "from" },
];
export const carInfoInputFieldCol2 = [
  { type: "text", label: "Buyer Name", value: "buyer_name" },
  { type: "text", label: "Buyer Phone", value: "buyer_phone" },
  { type: "textarea", label: "Buyer Address", value: "buyer_address" },
  { type: "date", label: "Sale Date", value: "sale_date" },
  {
    type: "date",
    label: "Registration On Date",
    value: "registration_on_date",
  },

  { type: "text", label: "Registration By", value: "registration_by" },
  { type: "text", label: "Reference By", value: "reference_by" },
  { type: "text", label: "Reference Phone", value: "ref_mobile" },
];

export const carInfoInputFieldSalesCol1 = [
  { type: "number", label: "Orginal Value(tk)", value: "order_value" },
  { type: "number", label: "Servicing", value: "servicing" },
  { type: "number", label: "Touch Up", value: "touch_up" },
  { type: "number", label: "Garage", value: "garage" },
  { type: "number", label: "Mobil filter plug", value: "mobil_filter_plug" },
  { type: "number", label: "Auto transmission oil", value: "auto_transmission" },
  { type: "number", label: "DVD Camera", value: "dvd_camera" },
  { type: "number", label: "Electrical works", value: "electrical_works" },
  {
    type: "number",
    label: "New Battery",
    value: "battary",
  },
  { type: "number", label: "Allow rim", value: "allow_rim" },
  { type: "number", label: "Spare Wheel", value: "spare_wheel" },
  // { type: "number", label: "Spare Wheel", value: "spare_wheel" },
  { type: "number", label: "Sale Price ", value: "sale_price" },
  { type: "enum", label: "Mode Of Payment", value: "mode_of_payment" },
  { type: "number", label: "First Payment", value: "first_payment" },
  { type: "number", label: "Second Payment", value: "second_payment" },
  { type: "number", label: "Third Payment", value: "third_payment" },


];
export const carInfoInputFieldSalesCol2 = [
  { type: "number", label: "Registration Misc", value: "registration_mic" },
  {
    type: "number",
    label: "Number Plate/Repel/Tools",
    value: "number_plate_repet_tool",
  },
  { type: "number", label: "Broker or Driver", value: "broker_or_driver" },
  { type: "number", label: "Showroom Commision", value: "showroom_commision" },
  {
    type: "number",
    label: "Spare Parts Purchase",
    value: "spare_parts_purchase",
  },
  { type: "number", label: "Seat Cover", value: "seat_cover" },
  { type: "number", label: "Floor Carpeting", value: "floor_carpeting" },
  { type: "number", label: "Steering Cover", value: "steeering_cover" },
  { type: "number", label: "Body Cover", value: "body_cover" },
  { type: "number", label: "Steel Bumper", value: "steel_bumper" },
  { type: "number", label: "Petrol", value: "petrol" },
  { type: "number", label: "Miscellaneous1", value: "miscellaneous1" },
  { type: "number", label: "Miscellaneous2", value: "miscellaneous2" },
  { type: "number", label: "Total Cost", value: "total_cost" },
  { type: "number", label: "Net Profit Or Loss", value: "net_profit_or_loss" },
];
