import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import DashBoard from "@/components/Shared/Layout/Dashboard";
import { useEffect, useState } from "react";
import { getSession } from "next-auth/react";
import router from "next/router";
import { UserService } from "services/user.service";


export default function Home() {

   //Authentication Section
   const [loading, setLoading] = useState<boolean>(true);
   useEffect(() => {
     const securePage = async () => {
    
       const session = await getSession();
       if (!session) {
         router.push("/auth/singin");
       } else setLoading(false);
     };
     securePage();
   }, []);
   if (loading) <p>Loading...........</p>;
  return (<>
      <Head>
        <title>GoldenMilesBd</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DashBoard/>

    
    </>
  );
}
